apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-cm
  namespace: roboshop
data:
 CART_ENDPOINT: "cart:8080"
 DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  replicas: 1
  selector:
  # These are labels to select pods.
    matchLabels:
     project: roboshop
     component: shipping
     tier: backend
# Pod defination
  template:
    metadata:
      labels:
       project: roboshop
       component: shipping
       tier: backend
    spec:
      containers:
      - name: shipping
        image: chakradhar05/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
           name: shipping-cm
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
         httpGet:
          path: /health
          port: liveness-port
         failureThreshold: 1
         periodSeconds: 10
        livenessProbe:
         httpGet:
          path: /health
          port: liveness-port
         failureThreshold: 1
         periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
       project: roboshop
       component: shipping
       tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080