apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    component: rabbitmq
    tier: db
  env: 
    RABBITMQ_DEFAULT_USER: "roboshop"
    RABBITMQ_DEFAULT_PASS: "roboshop123"
spec:
  replicas: 1
  selector:
  # These are labels to select pods.
    matchLabels:
     project: roboshop
     component: rabbitmq
     tier: db
# Pod defination
  template:
    metadata:
      labels:
       project: roboshop
       component: rabbitmq
       tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        imagePullPolicy: Always
        readinessProbe:
         tcpSocket:
          port: 5672
         initialDelaySeconds: 40
         periodSeconds: 10
      # Liveness probe should have more intial delay
        livenessProbe:
         tcpSocket:
          port: 5672
         initialDelaySeconds: 45
         periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
       project: roboshop
       component: rabbitmq
       tier: db
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672