apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
       project: roboshop
       component: mongodb
       tier: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017