apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
  # These are labels to select pods.
    matchLabels:
     project: roboshop
     component: mysql
     tier: db
# Pod defination
  template:
    metadata:
      labels:
       project: roboshop
       component: mysql
       tier: db
    spec:
      containers:
      - name: mysql
        image: chakradhar05/mysql:v1
        imagePullPolicy: Always
        readinessProbe:
         tcpSocket:
          port: 3306
         initialDelaySeconds: 15
         periodSeconds: 10
      # Liveness probe should have more intial delay
        livenessProbe:
         tcpSocket:
          port: 3306
         initialDelaySeconds: 45
         periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
       project: roboshop
       component: mysql
       tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306