apiVersion: v1
kind: ConfigMap
metadata:
  name: user-cm
  namespace: roboshop
data:
 MONGO: "true"
 REDIS_URL: "redis://redis:6379"
 MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: backend
spec:
  replicas: 1
  selector:
  # These are labels to select pods.
    matchLabels:
     project: roboshop
     component: user
     tier: backend
# Pod defination
  template:
    metadata:
      labels:
       project: roboshop
       component: user
       tier: backend
    spec:
      containers:
      - name: user
        image: chakradhar05/user:v1
        readinessProbe:
         tcpSocket:
          port: 8080
         initialDelaySeconds: 15
         periodSeconds: 10
        livenessProbe:
         tcpSocket:
          port: 8080
         initialDelaySeconds: 45
         periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
       project: roboshop
       component: user
       tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080